/*
 * DNS Service
 *
 * Sevice for managing DNS with route53
 *
 * API version: 0.0.1
 * Contact: iitr.animesh@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package route53dns

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	CreateRoute53HostedZoneRecord(http.ResponseWriter, *http.Request)
	ListRoute53HostedZoneRecords(http.ResponseWriter, *http.Request)
	ListRoute53HostedZones(http.ResponseWriter, *http.Request)
	Route53CreatednsfromlbtagsPut(http.ResponseWriter, *http.Request)
	Route53DomainsDomainRecordsNameRecordTypeDelete(http.ResponseWriter, *http.Request)
	Route53DomainsDomainRecordsNameRecordTypeGet(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	CreateRoute53HostedZoneRecord(context.Context, string, DnsRecord) (ImplResponse, error)
	ListRoute53HostedZoneRecords(context.Context, string) (ImplResponse, error)
	ListRoute53HostedZones(context.Context) (ImplResponse, error)
	Route53CreatednsfromlbtagsPut(context.Context, LoadBalancerInput) (ImplResponse, error)
	Route53DomainsDomainRecordsNameRecordTypeDelete(context.Context, string, string, DnsRecordType) (ImplResponse, error)
	Route53DomainsDomainRecordsNameRecordTypeGet(context.Context, string, string, DnsRecordType) (ImplResponse, error)
}
